spring.application.name=Nexora
spring.datasource.url=jdbc:mysql://localhost:3306/nexora_db
spring.datasource.username=root
spring.datasource.password=shreyas

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect